modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="brassmanmod"
displayName="Brass Man"
credits="BlackRedCoded"
authors="BlackRedCoded"
description='''A Create addon that brings Iron Man-inspired technology using brass and pneumatic power.'''

[[dependencies.brassmanmod]]
modId="neoforge"
mandatory=true
versionRange="[21.1.118,)"
ordering="NONE"
side="BOTH"

[[dependencies.brassmanmod]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.brassmanmod]]
modId="create"
mandatory=false
versionRange="[6.0.6,)"
ordering="NONE"
side="BOTH"
